#!/bin/bash

if [ ! -f wp-cli.phar ]; then
	echo "downloading wp-cli"
	echo "--------------------------------------------------------"
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  echo "--------------------------------------------------------"
  echo "wp-cli installed"
fi

min=10000
max=99999
number=$[($RANDOM % ($[$max - $min] + 1)) + $min]
tmpfile=/tmp/wpinit${number}.log
adminpassword=$(openssl rand -base64 8)
adminloginsuffix=$[($RANDOM % ($[$max - $min] + 1)) + $min]
clientadminpassword=$(openssl rand -base64 8)
clienteditorpassword=$(openssl rand -base64 8)
currentpath=$(pwd)

echo $adminpassword

echo $number

echo $tmpfile

if [ -f $tmpfile ]; then
  rm $tmpfile
fi

touch $tmpfile

clear

if [ -d $currentpath"/wp-content" ]; then
  echo -n "Worpdress files found. Delete Files? [y/N]: "
  read DELETE
  if [[ $DELETE = [Yy] ]]; then
    rm -rf $currentpath"/*"
    echo "Empty folder $currentpath"
  else
    exit 1
  fi
fi

echo "WordPress Installation"
php wp-cli.phar core download --locale=fr_FR

echo 'DB Informations'
read -p 'DB name : ' dbname
read -p 'DB user : ' dbuser
read -p 'DB password : ' dbpassword

echo "Database" >> $tmpfile
echo "----------------------------" >> $tmpfile
echo "DB name : $dbname" >> $tmpfile
echo "DB user : $dbuser" >> $tmpfile
echo "DB password : $dbpassword" >> $tmpfile
echo "DB prefix : wp${number}_" >> $tmpfile
echo "----------------------------" >> $tmpfile

php wp-cli.phar core config --dbname=$dbname --dbuser=$dbuser --dbpass=$dbpassword --dbprefix=wp${number}_ --locale=fr_FR --extra-php <<PHP
if ( !defined('WP_DEBUG') ) define('WP_DEBUG', true);
if ( !defined('DISALLOW_FILE_EDIT') ) define('DISALLOW_FILE_EDIT', true);
if ( !defined('AUTOMATIC_UPDATER_DISABLED') ) define('AUTOMATIC_UPDATER_DISABLED', true);
if ( !defined('WP_AUTO_UPDATE_CORE') ) define('WP_AUTO_UPDATE_CORE', false);
PHP

php wp-cli.phar db reset

echo 'Site Informations'
read -p 'Sitename (htpasswd login & theme name)  : ' sitename
read -p 'URL (full) : ' url
read -p 'Title : ' title
read -p 'Admin login : ' adminlogin
read -p 'Admin email : ' adminemail

echo "Site" >> $tmpfile
echo "----------------------------" >> $tmpfile
echo "Sitename : $sitename" >> $tmpfile
echo "URL : $url" >> $tmpfile
echo "Title : $title" >> $tmpfile
echo "Admin login : ${adminlogin}_${adminloginsuffix}" >> $tmpfile
echo "Admin email : $adminemail" >> $tmpfile
echo "Admin password : $adminpassword" >> $tmpfile
echo "Admin URL : ${url}/wp-admin" >> $tmpfile
echo "----------------------------" >> $tmpfile

echo ""
echo "Install in progress... please wait"

php wp-cli.phar core install --url="$url" --title="$title" --admin_user="${adminlogin}_${adminloginsuffix}" --admin_password="$adminpassword" --admin_email="$adminemail" --skip-email
php wp-cli.phar option update siteurl $url
php wp-cli.phar option update home $url

#echo "client admin"
#read -p 'client admin login : ' clientadminlogin
#read -p 'client admin email : ' clientadminemail

#echo "client admin" >> $tmpfile
#echo "----------------------------" >> $tmpfile
#echo "client admin login : $clientadminlogin" >> $tmpfile
#echo "client admin email : $clientadminemail" >> $tmpfile
#echo "client admin password : $clientadminpassword" >> $tmpfile
#echo "----------------------------" >> $tmpfile

#php wp-cli.phar user create "${clientadminlogin}" "${clientadminemail}" --role=administrator --user_pass="${clientadminpassword}"

#echo "client editor"
#read -p 'client editor login : ' clienteditorlogin
#read -p 'client editor email : ' clienteditoremail

#echo "client editor" >> $tmpfile
#echo "----------------------------" >> $tmpfile
#echo "client editor login : $clienteditorlogin" >> $tmpfile
#echo "client editor email : $clienteditoremail" >> $tmpfile
#echo "client editor password : $clienteditorpassword" >> $tmpfile
#echo "----------------------------" >> $tmpfile

#php wp-cli.phar user create "${clienteditorlogin}" "${clienteditoremail}" --role=editor --user_pass="${clienteditorpassword}"

echo "Defining permalinks"
php wp-cli.phar rewrite structure '/%postname%/'

echo "Cleaning default WordPress installation"
php wp-cli.phar plugin delete hello-dolly
php wp-cli.phar plugin delete akismet
php wp-cli.phar post delete 1
php wp-cli.phar option update blogdescription ''
php wp-cli.phar option update use_smilies 0
php wp-cli.phar option update blog_public 0

cd wp-content/themes
git clone --depth 1 https://github.com/Net-Com/fwk.git genesis
git clone --depth 1 https://github.com/Net-Com/wp-base-theme.git $sitename
#sed 's/Net.Com child theme/${title}/g' ./${sitename}/style.css > ./${sitename}/style.css
cd ../../

php wp-cli.phar theme activate ${sitename}
php wp-cli.phar theme delete twentyfifteen
php wp-cli.phar theme delete twentyseventeen
php wp-cli.phar theme delete twentysixteen

php wp-cli.phar plugin install pods --activate
php wp-cli.phar plugin install panda-pods-repeater-field --activate
php wp-cli.phar plugin install redux-framework --activate
php wp-cli.phar plugin install members --activate
php wp-cli.phar plugin install ewww-image-optimizer --activate
php wp-cli.phar plugin install regenerate-thumbnails --activate
php wp-cli.phar plugin install crop-thumbnails --activate
php wp-cli.phar plugin install better-wp-security --activate
php wp-cli.phar plugin install wordpress-seo --activate
php wp-cli.phar plugin install redirection --activate
php wp-cli.phar plugin install broken-link-checker --activate
php wp-cli.phar plugin install ps-auto-sitemap --activate
php wp-cli.phar plugin install google-analytics-dashboard-for-wp --activate
php wp-cli.phar plugin install material-admin-theme --activate
php wp-cli.phar plugin install tabify-edit-screen --activate
php wp-cli.phar plugin install tinymce-advanced --activate
php wp-cli.phar plugin install wp-config-file-editor --activate
php wp-cli.phar plugin install debug-bar --activate
php wp-cli.phar plugin install debug-bar-actions-and-filters-addon --activate
php wp-cli.phar plugin install kint-debugger --activate
php wp-cli.phar plugin install simply-show-hooks --activate

php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/gravityforms.zip --activate
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/profilepress.zip
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/admin-columns-pro.zip --activate
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/wp-rocket.zip --activate
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/nc_tpl_render.zip --activate
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/Pods-Edit-Custom.zip
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/Pods-Genesis-Maker.zip --activate
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/nc_disable_delete_page.zip --activate
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/nc_responsive_table.zip --activate
php wp-cli.phar plugin install ./wp-content/themes/${sitename}/base/Plugin-Activation/plugins/nc_search.zip --activate

echo "${sitename}:MqiKIHH7L1K9s" > .htpasswd

htaccessinfo=$(cat htaccess.add)

echo "AuthUserFile ${currentpath}/.htpasswd" >> htaccess.add

cat htaccess.add .htaccess > .htaccess
rm htaccess.add

echo "Regenerating permalinks"
php wp-cli.phar rewrite flush --hard

echo "Creating homepage"
php wp-cli.phar post create --post_type=page --post_title=Home --post_status=publish --post_author=$(php wp-cli.phar user get ${adminlogin}_${adminloginsuffix} --field=ID --format=ids)
php wp-cli.phar option update show_on_front 'page'
php wp-cli.phar option update page_on_front $(php wp-cli.phar post list --post_type=page --post_status=publish --posts_per_page=1 --pagename=home --field=ID --format=ids)

php wp-cli.phar menu create "Main Navigation"
export IFS=" "
for pageid in $(php wp-cli.phar post list --order="ASC" --orderby="date" --post_type=page --post_status=publish --posts_per_page=-1 --field=ID --format=ids); do
	php wp-cli.phar menu item add-post main-navigation $pageid
done

php wp-cli.phar menu location assign main-navigation primary

echo "Update language"
php wp-cli.phar core language update

cat $tmpfile

mail -s "detail ${url}" ${adminemail} < $tmpfile
rm $tmpfile
